runtime: python27
application: cs498-174208
api_version: 1
threadsafe: true
version: 1

handlers:
- url: /
  static_files: WebContent/DataGraph.html
  upload: WebContent/DataGraph.html

- url: /(.*)
  static_files: WebContent/\1
  upload: WebContent/(.*)
